### PR TITLE
Use pagination for polling YouTube live chat messages

### PR DESCRIPTION
**Pull request by Susko3**
Changes the YouTube `ChatClient` to use pagination for polling [`liveChatMessages`](https://developers.google.com/youtube/v3/live/docs/liveChatMessages/list).

The old way would get every recent message each in each request, leading to a lot of unnecessary data transfer and very high API usages leading to my 10k quota being used up very quickly. Not the mention the hash map storing every single message ID -- can be considered a memory leak.

10k queries used, but only 2k calls to the API == ~5 messages per request. Since I was testing, I sent ~30 messages in chat, not even close to the ~5 per request.

image

image

So instead of querying every message, the requests are now paginated and return only new messages (sent after the last request). I've not yet tested this as I've run out of quota for today. I can test tomorrow if you want. I've done a rudimentary check with the Google API Explorer, manually copying the token values into the new request.

### CODE REVIEW

**Comment by SaviorXTanren** [comment]
Have you had a chance to test this out?

**Comment by Susko3** [comment]
Just got around to testing it: works well. Still hammers the quota.

It's polling every ~1 second. But using up ~280 / 60 = 4.6666666666 "quotas" per second.

image

image

**Comment by Susko3** [comment]
There's `minimumPollTimeMilliseconds`, so it's tolerable.

https://github.com/SaviorXTanren/StreamingClientLibrary/blob/088322a4d2f6fecc0f2dbc036f630c2bc4428c18/YouTube/YouTube.Base/Clients/ChatClient.cs#L70

**Comment by SaviorXTanren** [comment]
> Just got around to testing it: works well. Still hammers the quota.
> 
> It's polling every ~1 second. But using up ~280 / 60 = 4.6666666666 "quotas" per second.

Yea, unfortunately that's just the nature of the beast for YouTube's chat system. We implement some logic to force it to have an increasing latency to polling when there are no new messages up to a maximum threshold. So we try to offset it as best as possible. I'll give this a try on my end and see how things look. Thanks!

**Pull request merged**
